[hw08_envdir_tool]
Ayna5/hw-golangOtus pull request #10
Opened 2021-03-11 22:49 UTC by Ayna5

## Домашнее задание №8 «Утилита envdir» 

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-03-17 04:39 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/28086/9020/

Здравствуйте!
Хорошая работа, видно, вы долго мучались. Но нужно ещё чуть поднажать :)

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/testdata/env/EMPTY
> -
почему изменился этот файл?

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/main.go
> +		fmt.Println(errors.Wrapf(err, "can't get environment variables from dir %v:", d)) // permit:fmt.Println
зачем здесь Wrap?

WithMessage скорее: стек не нужен, и так на верхнем уровне

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +		os.Exit(1)
лишнее в этой функции

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +		fmt.Println(errors.New("cmd length must be greater than 0")) // permit:fmt.Println
выключите себе permit, чтобы повсюду не писать комментарии

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +			return 1
напечатать бы ошибоньку

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +		return 1
здесь бы возвращать код, именно с которым завершился Run

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader_test.go
> +		expectedEnv := make(Environment)
вы могли сразу объявить через
```
Environment{
    "ADDED": ...,
}
```

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +	res := make(map[string]EnvValue)
преаллокация

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +		if file.IsDir() {
скорее `if !file.IsRegular`

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +		openFile, err := os.OpenFile(dir+"/"+file.Name(), os.O_RDONLY, os.ModeDir)
filepath.Join !!!

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +		if r.Size() == 0 {
в этот момент вы ничего и не прочитали, reader точно знает Size()?

этот код работает?

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +			delete(res, file.Name())
NeedRemove не просто так сделан в EnvValue - вы удаляете переменную из мапы, но это никак не влияет на окружение выше

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +			if errors.Is(err, io.EOF) {
io.EOF не проверяют через errors.Is

но можно оставить

2021-03-17 04:39 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +			openFile.Close()
а во всех continue выше?

потеряли закрытия файлов

2021-03-17 05:15 UTC, Ayna5 commented on hw08_envdir_tool/testdata/env/EMPTY
> -
случайно изменила, вернула как было

2021-03-17 05:29 UTC, Ayna5 commented on hw08_envdir_tool/env_reader.go
> +		if file.IsDir() {
не поняла почему
мы же по файлам в директории проходим и нам нужны только файлы

2021-03-17 05:35 UTC, Ayna5 commented on hw08_envdir_tool/env_reader.go
> +	res := make(map[string]EnvValue)
не поняла про преаллокацию
мне же нужно инициализировать мапу

2021-03-21 08:33 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +	res := make(map[string]EnvValue)
```res := make(map[string]EnvValue, len(fileInfo))```

2021-03-21 08:35 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +		if file.IsDir() {
и что не так? :)

если файл нерегулярный (директория, /dev/null, etc), то `continue`

2021-03-21 08:41 UTC, Antonboom approved these changes
Здравствуйте!

Я до сих пор не понимаю, как у вас проходят тесты, думаю - это связано с тем, что вы все-таки поменяли EMPTY файл (в обратном случае его бы не было в пулреквесте).

Принято с натяжкой, 7 / 10

2021-03-21 08:41 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +		if file.IsDir() {
и что не так? :)

если файл нерегулярный (директория, /dev/null, etc), то continue

2021-03-21 08:41 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +	res := make(map[string]EnvValue)
res := make(map[string]EnvValue, len(fileInfo))

2021-03-21 08:41 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +		if err == &er {
использовать `errors.As`!

2021-03-21 08:41 UTC, Antonboom commented on hw08_envdir_tool/env_reader.go
> +			openFile.Close()
делать через defer

2021-03-21 08:41 UTC, Antonboom commented on hw08_envdir_tool/executor.go
> +		err := os.Setenv(key, val.Value)
и где использование NeedRemove?

2021-03-23 19:23 UTC, merged