[hw02_unpack_string] added function unpack string
Ayna5/hw-golangOtus pull request #2
Opened 2020-12-21 23:57 UTC by Ayna5

## Домашнее задание №2 «Распаковка строки»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-12-27 05:08 UTC, kulti requested changes
Получилось сложное и запутанное решение. Разбиение на методы упрощает код основного метода Unpack — это хорошая практика, продолжайте ее использовать.

Также в решение есть очевидные ошибки и, думаю, множество неочевидных из-за переусложненных условий. Повторюсь, что проблема в том, что используются проверки не только текущего символа, но и нескольких символов вокруг от i-1 до i+3.

Предлагаю поступить так:
1. Делать задание без звездочки (без экранирования).
2. Забыть про это решение.
3. Не использовать индекс i, а сохранять только предыдущий символ в отдельной переменной (этого достаточно). 

В качестве подсказки дам такую заготовку:
```
	var prevRune rune
	for _, r := range s {
		switch r {
		case '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
		default:
		}
	}
```

Здесь нужно добавить немного кода вне цикла и немного кода внутрь case и default. Попробуйте подойти к задаче по другому с теми ограничениями, которые я описал. Должно получится простое решение. Если появятся вопросы, приходите в слак, постараюсь помочь.

2020-12-29 06:51 UTC, kulti requested changes
Решение становится все лаконичнее и лаконичнее :) Судя по всему, еще есть проблемы в понимании Go из-за этого присутствуют логические ошибки.

Предлагаю подойти к задаче по другому, чтобы получить компактное и простое решение без лишних проверок:
1. Если текущая руна цифра, то
1.1. если предыдущей руны нет, то это ошибка;
1.2. если есть, то размножить предыдущую руну.
2. Если текущая руна просто символ, то
2.1. если есть предыдущая руна, то надо ее записать.
3. Если цикл закончился и есть предыдущая руна, то надо ее записать.

Т.е. нужно запоминать не только предыдущую руну, но и факт ее наличия.

Анализ строки вида ab4c3 будет проходить, как последовательный разбор простых подстрок: a, b4 и c3.

2020-12-29 06:51 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if i == len(s)-len(string(r)) {
Это очень странная проверка. Не понимаю, что именно хотелось проверить. `len(s)` — это длина строки в байтах, а в `len(string(r))` вообще никакого смысла нет, т.к. это будет всегда `1`.

2020-12-29 06:51 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if unicode.IsDigit(prevRune) {
Из-за `unicode.IsDigit` получается некоторая неконсистентность в том, что считается цифрой. В case перечислены только 10 ascii-цифр, а в `unicode.IsDigit` их значительно больше.

2021-01-17 12:37 UTC, Ayna5 commented on hw02_unpack_string/unpack.go
> +			if i == len(s)-len(string(r)) {
не всегда будет 1)
в случае кириллицы и каких-то символов руна равна 2-м)
Я проверяла

2021-01-17 13:10 UTC, kulti commented on hw02_unpack_string/unpack.go
> +			if i == len(s)-len(string(r)) {
Да, действительно. Я сам же и написал, что len от строки — это длинна в байтах. Еще меня эта i с толку сбила. Оказывается, это индекс в слайсе байт, а не рун. Век живи — век учись. Довольно неочевидная вещь, как по мне :)

Тогда осталось убрать неконсистентность IsDigit и перечисление цифр.  Например, заменить switch на if:
```
if unicode.IsDigit(r) {
	// ...
} else {
	// ...
}
```

Можно и со switch оставить, но читаться, имхо, будет хуже:
```
switch {
case unicode.IsDigit(r):
	// ...
default:
	// ...
}
```

После этого приму дз на 8/10.

2021-01-17 15:22 UTC, kulti approved these changes
ДЗ принято - 8/10

2021-03-23 19:56 UTC, closed without merging