Hw04 lru cache
Ayna5/hw-golangOtus pull request #4
Opened 2021-02-07 22:00 UTC by Ayna5

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-02-10 06:26 UTC, balabanovds requested changes
Хорошая работа, но есть замечания

Также отмечу, что нет теста на логику выталкивания из кэша редко используемых элементов.

.. и  в МР попали файлы из других ДЗ

https://otus.ru/teacher-lk/homework/28086/9018/

2021-02-10 06:26 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	return &lruCache{
а если передали capacity 0 или меньше, будет ли валидным кеш?

2021-02-10 06:26 UTC, balabanovds commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
в этой проверке нет необходимости, у указателя zero value == nil

2021-02-10 06:26 UTC, balabanovds commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
эта тоже лишняя проверка

2021-02-12 00:00 UTC, Ayna5 commented on hw04_lru_cache/cache.go
> +	return &lruCache{
нет
если будет 0, то получается ничего не закешируется

2021-02-12 10:13 UTC, balabanovds approved these changes
Уже намного лучше.
Осталось замечание, тем не менее работа зачтена

8/10

2021-02-12 10:13 UTC, balabanovds commented on hw04_lru_cache/cache.go
> +	if capacity > 0 {
Вы пишете либу, и скорее всего ей кто-то будет пользоваться.
Пользователю лучше в явном виде сказать об ошибке, а не возвращать nil.
Сигнатуру можно менять

2021-02-18 20:08 UTC, balabanovds approved these changes
Уже совсем хорошо!
Еще  лучше экспортировать ошибку, чтобы на нее могли проверять пользователи. 
10/10

2021-02-20 17:18 UTC, balabanovds approved these changes
👌

2021-02-20 17:21 UTC, merged